../icons/klickety-16.xpm /usr/share/pixmaps
../icons/klickety.xpm /usr/share/pixmaps
usr/games/klickety
usr/share/applications/org.kde.klickety.desktop
usr/share/applications/org.kde.ksame.desktop
usr/share/doc/HTML/en/klickety/
usr/share/icons/hicolor/128x128/apps/klickety.png
usr/share/icons/hicolor/128x128/apps/ksame.png
usr/share/icons/hicolor/16x16/apps/klickety.png
usr/share/icons/hicolor/16x16/apps/ksame.png
usr/share/icons/hicolor/22x22/apps/klickety.png
usr/share/icons/hicolor/22x22/apps/ksame.png
usr/share/icons/hicolor/32x32/apps/klickety.png
usr/share/icons/hicolor/32x32/apps/ksame.png
usr/share/icons/hicolor/48x48/apps/klickety.png
usr/share/icons/hicolor/48x48/apps/ksame.png
usr/share/icons/hicolor/64x64/apps/klickety.png
usr/share/icons/hicolor/64x64/apps/ksame.png
usr/share/kconf_update/
usr/share/klickety/klickety.kcfg
usr/share/klickety/themes/
usr/share/knotifications5/klickety.notifyrc
usr/share/kxmlgui5/klickety/klicketyui.rc
