../icons/klickety-16.xpm /usr/share/pixmaps
../icons/klickety.xpm /usr/share/pixmaps
usr/games/klickety
usr/share/applications/kde4/klickety.desktop
usr/share/applications/kde4/ksame.desktop
usr/share/doc/kde/HTML/*/klickety
usr/share/icons/hicolor/128x128/apps/klickety.png
usr/share/icons/hicolor/128x128/apps/ksame.png
usr/share/icons/hicolor/16x16/apps/klickety.png
usr/share/icons/hicolor/16x16/apps/ksame.png
usr/share/icons/hicolor/22x22/apps/klickety.png
usr/share/icons/hicolor/22x22/apps/ksame.png
usr/share/icons/hicolor/32x32/apps/klickety.png
usr/share/icons/hicolor/32x32/apps/ksame.png
usr/share/icons/hicolor/48x48/apps/klickety.png
usr/share/icons/hicolor/48x48/apps/ksame.png
usr/share/icons/hicolor/64x64/apps/klickety.png
usr/share/icons/hicolor/64x64/apps/ksame.png
usr/share/kde4/apps/kconf_update/klickety-2.0-inherit-ksame-highscore.pl
usr/share/kde4/apps/kconf_update/klickety.upd
usr/share/kde4/apps/klickety/*
